# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-27 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField()),
                ('note', models.TextField()),
                ('additional_note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Headings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarriff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField()),
                ('heading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_heading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_sub_heading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cd', models.IntegerField()),
                ('description', models.TextField()),
                ('statistical_unit', models.TextField()),
                ('general_rate_of_duty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eu_rate_of_duty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('efta_rate_of_duty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sadc_rate_of_duty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mercosur_rate_of_duty', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
