# Generated by Django 4.1.2 on 2022-10-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tarriff",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("heading", models.CharField(max_length=30)),
                ("commodity_code", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=30)),
                ("statistical_unit", models.CharField(max_length=30)),
                ("general_rate_of_duty", models.CharField(max_length=30)),
                ("mtf_rate_of_duty", models.CharField(max_length=30)),
            ],
        ),
    ]
