# Generated by Django 4.1.2 on 2022-10-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChapterSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chapter", models.CharField(max_length=30)),
                ("section", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="tarriff",
            name="description",
            field=models.CharField(max_length=100),
        ),
    ]
