# Generated by Django 4.1.2 on 2023-01-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_chaptersection_alter_tarriff_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chaptersection",
            name="chapter",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="chaptersection",
            name="description",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="chaptersection",
            name="section",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tarriff",
            name="commodity_code",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tarriff",
            name="description",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tarriff",
            name="heading",
            field=models.CharField(max_length=100),
        ),
    ]
