# Generated by Django 4.1.2 on 2023-01-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_chaptersection_chapter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chaptersection",
            name="chapter",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="chaptersection",
            name="section",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tarriff",
            name="general_rate_of_duty",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tarriff",
            name="mtf_rate_of_duty",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
