# Generated by Django 4.1.2 on 2023-01-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_chaptersection_chapter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarriff",
            name="statistical_unit",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
